/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-login': RouteRecordInfo<'admin-login', '/admin/login', Record<never, never>, Record<never, never>>,
    'analytics': RouteRecordInfo<'analytics', '/analytics', Record<never, never>, Record<never, never>>,
    'certificates': RouteRecordInfo<'certificates', '/certificates', Record<never, never>, Record<never, never>>,
    'courses': RouteRecordInfo<'courses', '/courses', Record<never, never>, Record<never, never>>,
    'courses-categories': RouteRecordInfo<'courses-categories', '/courses/categories', Record<never, never>, Record<never, never>>,
    'courses-create': RouteRecordInfo<'courses-create', '/courses/create', Record<never, never>, Record<never, never>>,
    'dashboards-lms': RouteRecordInfo<'dashboards-lms', '/dashboards/lms', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'media': RouteRecordInfo<'media', '/media', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'payments-coupons': RouteRecordInfo<'payments-coupons', '/payments/coupons', Record<never, never>, Record<never, never>>,
    'payments-subscriptions': RouteRecordInfo<'payments-subscriptions', '/payments/subscriptions', Record<never, never>, Record<never, never>>,
    'payments-transactions': RouteRecordInfo<'payments-transactions', '/payments/transactions', Record<never, never>, Record<never, never>>,
    'quizzes-bank': RouteRecordInfo<'quizzes-bank', '/quizzes/bank', Record<never, never>, Record<never, never>>,
    'quizzes-exams': RouteRecordInfo<'quizzes-exams', '/quizzes/exams', Record<never, never>, Record<never, never>>,
    'quizzes-results': RouteRecordInfo<'quizzes-results', '/quizzes/results', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'student-dashboard': RouteRecordInfo<'student-dashboard', '/student/dashboard', Record<never, never>, Record<never, never>>,
    'students': RouteRecordInfo<'students', '/students', Record<never, never>, Record<never, never>>,
    'students-enrollments': RouteRecordInfo<'students-enrollments', '/students/enrollments', Record<never, never>, Record<never, never>>,
  }
}
